name: Build Plugin

on:
  push:
    branches:
      - test
#    paths:
#      - "**/plugin/**"

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

#      - name: Cache Gatsby
#        uses: actions/cache@v3
#        id: gatsby
#        with:
#          path: |
#            .cache
#            public
#          # we have to not include the string "gatsby" in the cache name.
#          # otherwise, the cache will be busted on every build.
#          key: ${{ runner.os }}-build-cache

      - name: Install Packages
        run: npm ci

      - name: Build
        run: npm run build:plugin

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          files: |
            manifest.json
            build/**

#      - name: Push to gh-pages branch
#        uses: peaceiris/actions-gh-pages@v3
#        if: ${{ github.ref == 'refs/heads/main' }}
#        with:
#          github_token: ${{ secrets.GITHUB_TOKEN }}
#          publish_dir: ./public
#          # don't keep a history of all the commits to the gh_pages branch
#          force_orphan: true
#          cname: routedapp.org
